StairDashINSPIRE2019/StairDash/Controllers/StairDashController.cs
using StairDash.StairDataServiceReference;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace StairDash.Controllers
{
    public class StairDashController : Controller
    {


        // GET: StairDash
        public ActionResult Index(int? steps)
        {
            StairDataServiceReference.ServiceClient srv = new StairDataServiceReference.ServiceClient();



            int mileStone = 300;
            float percent;
            
            var list = srv.GetAllData(0);
            var sortedList = list;
            int i = 1;
            var placeholder = list[0];


            while (i < list.Length)
            {
                if (list[i].Score > list[i - 1].Score)
                {
                    placeholder = list[i - 1];
                    list[i - 1] = list[i];
                    list[i] = placeholder;
                }

                i++;
            }


            if (steps == null)
            {
                steps = 0;
                ViewBag.steps = steps;
            }
            else
            {
                ViewBag.steps = steps;
            }


            steps = 122;
            ViewBag.steps = steps;



            percent = (((float)steps / (float)mileStone) * 100.0f);
            percent = (float)Math.Round(percent, 1);
            ViewBag.stepPercent = percent;

            if (percent > 100)
            {
                percent = 100;
            }

            ViewBag.gaugePercent = Math.Round(percent / 5.0) * 5;
            ViewBag.gaugeDisplayPercent = percent;




            ViewBag.mileStone = mileStone;
            ViewBag.teams = list;

            return View();
        }


        public ActionResult TeamView()
        {
            StairDataServiceReference.ServiceClient srv = new StairDataServiceReference.ServiceClient();

            var list = SortTeams(srv.GetAllData(0));

            ViewBag.teams = list;

            return View();
        }


        private StairDataServiceReference.ServiceTeamObj[] SortTeams(ServiceTeamObj[] list)
        {
            var newlist = list;
            int i = 1;
            int n = 0;
            var placeholder = list[0];

            var loop = true;

            while (n < list.Length)
            {
                while (i < list.Length)
                {
                    if (list[i].Score > list[i - 1].Score)
                    {
                        placeholder = list[i - 1];
                        list[i - 1] = list[i];
                        list[i] = placeholder;
                    }

                    i++;
                }

                n++;
            }



            return list;
        }
    }
}

StairDashINSPIRE2019/StairDash/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("StairClimber", "Index", "StairDash", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("MyView", "Index", "StairDash", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("TeamView", "TeamView", "StairDash", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>